version: "3.1"

services:
  lockbox:
    build:
      context: .
      dockerfile: ./lockbox/Dockerfile
    environment:
      PORT: 15001

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "15003:15003"
    environment:
      PORT: 15002
      HTTP_PORT: 15003

  cracker:
    build:
      context: .
      dockerfile: ./cracker/Dockerfile
    environment:
      LOCKBOX_ENDPOINT: lockbox:15001
      FRONTEND_ENDPOINT: frontend:15002
      WORKERS: 0
      MEMLEAK: "FALSE"
      CPULEAK: "FALSE"
    depends_on:
      - lockbox
      - frontend

